# Generated by Django 3.1.1 on 2020-10-02 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_actualizado', models.DateTimeField(auto_now_add=True)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizar', models.IntegerField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinica.modelobase')),
                ('desc_servicio', models.CharField(help_text='Tipo de servicio', max_length=128, unique=True)),
            ],
            bases=('clinica.modelobase',),
        ),
    ]
