# Generated by Django 3.1.1 on 2020-10-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20201002_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelobase',
            name='hora_actualizado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelobase',
            name='horario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
