# Generated by Django 3.1.1 on 2020-10-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20201002_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinica.modelobase')),
                ('description', models.CharField(help_text='SubCategory Description', max_length=128, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.category')),
            ],
            bases=('clinica.modelobase',),
        ),
    ]
