# Generated by Django 3.1.1 on 2020-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc_servicio',
            field=models.CharField(help_text='Tipo de servicio', max_length=128),
        ),
    ]
